### ISSUE TITLE
Use metadata for the progressbar

### ISSUE THREAD

**Issue by Syntasu** [Syntasu/synn-loadscreen#18]
**Abstract**
The current issue is that the progress bar seems to ignore additional orders in loading screen, since we always do `Math.max(total / done)`, this would mean it would always adopt the highest value and this happens when total is set to the amount of the first order, since after the first order is done, the next will be received and added to the total.

**Resolution**
This could be pretty easily resolved by relying on some metadata for the progress, something like this:
```
INIT_CORE = {
    orders = 3
},
BEFORE_MAP: {
   orders =2,
},
```

We would only need to know the amount of orders and the initialization functions, since we could just make a "placeholder" for these value and assign the total values at a later point. Revising the total progress per stage method would needed.

**EDIT**
Adding the functions would be a nice thing to have as well, since some client suffer from race conditions where an entire init function is not registered, thus we would to make an educated guess to which function this belongs to.  
###### Note; can't we just pull from the FiveM repo the function definitions?

One of the issue is that this metadata might become out-dated if FiveM or R* decided to add or alter the init methods or order count.

**TODO**
- [ ] Re-write the progress bar
- [ ] Unit test it
- [ ] Graceful fallback if new methods are added (i.e. test via Unit testing.)
- [ ] Some metadata generator tool, allowing people to update themselves.
- [ ] Someway of detecting which function belongs to what.
